На рынке новостроек появилось предложение от застройщика "Гарантия" — двухкомнатная квартира общей площадью 59.50 кв.м, жилой площадью 31.40 кв.м на 19-м этаже 22-х этажного дома. В доме 2 подъезда. Цена за квадратный метр квартиры у этого застройщика составляет 60550 рублей.

In [27]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
apartment

array([5.950e+01, 3.140e+01, 1.900e+01, 2.000e+00, 6.055e+04, 2.000e+00])

В NumPy вектор и массив - одно и то же. 

Исключение - понятие вектор-столбец и вектор-строка - фактически двумерные массивы, где один из атрибутов shape равен 1.

In [28]:
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


Упростим себе задачу оценки новой квартиры — сгенерируем новый признак — отношение жилой площади к общей. 

А от старых признаков смело избавимся, сократив векторное пространство нашего объекта.

In [29]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
share_living_space

0.5277310924369748

Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. 

Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:

In [30]:
apartment = np.delete(apartment, [0, 1])
apartment

array([1.900e+01, 2.000e+00, 6.055e+04, 2.000e+00])

И в завершение добавим в конец нашего массива новый признак share_living_space, который сочетает в себе смысл двух старых признаков:

In [31]:
apartment = np.append(apartment, share_living_space)
print(len(apartment))
apartment

5


array([1.90000000e+01, 2.00000000e+00, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [32]:
wife = np.array([120, 150, 90])
husband = np.array([130, 130, 130])
mother_in_law = np.array([2, 3, 2.5])

print(wife)
print(husband)
print(mother_in_law)

# Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля. 
mother_in_law = mother_in_law * 72
print(mother_in_law)

# Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.
wife + husband + mother_in_law

[120 150  90]
[130 130 130]
[2.  3.  2.5]
[144. 216. 180.]


array([394., 496., 400.])

In [33]:
# Найдите линейную комбинацию векторов
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])

xq = 2
yq = -3
uq = 5

x * xq + y * yq + u * uq

array([7, 7])

Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели.

In [34]:
done = np.array([3,4,5,9])
sold = np.array([1,5,3,6])

sold * 400 - done * 200


array([-200, 1200,  200,  600])

Найдите скалярное произведение векторов 


In [35]:
x = np.array([4,5,-1])
y = np.array([2,0,1])
np.dot(x, y)

7

Вычислите длину вектора . Ответ округлите до сотых.

In [36]:
x = np.array([4,6,1])
np.dot(x,x)**.5

7.280109889280518

##  Задача 1. Условие

В Hut_Paradise_DF представлен фрагмент базы данных агенства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [37]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
display(Hut_Paradise_DF)                                

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

Найдите вектор параметров квартиры номер 5:

In [38]:
Hut_Paradise_DF.values[4]

array([40, 33,  1,  6, 20, 16])

Найдите вектор этажей всех квартир:

In [39]:
Hut_Paradise_DF.values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

На каком этаже расположена квартира номер 3?

In [40]:
Hut_Paradise_DF.values[2,3]

10

Найдите количество квартир:

In [41]:
len(Hut_Paradise_DF)

9

Вычислите вектор нежилой площади:

In [42]:
Hut_Paradise_DF.values[:,1] - Hut_Paradise_DF.values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны:

In [43]:
rate = 4 / 10
print(rate)
Hut_Paradise_DF.values[:,0] * rate

0.4


array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. 

Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [47]:
demo_length = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
print(np.dot(Hut_Paradise_DF.values[:,4], demo_length))
Hut_Paradise_DF.values[:,4]@demo_length

1348


1348

## Задача 2. Условие
Даны три вектора:

In [49]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [52]:
comb = v * 2 + w * -3

Будет ли эта комбинация ортогональна вектору ?

In [54]:
u@comb == 0

True

Нормируйте векторы u, v, w.

В ответ запишите, округлив до трёх знаков после точки: