## Задача. Условие
Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [13]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

In [14]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [15]:
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Доходы представлены до уплаты налогов. Налоговая ставка - 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте матрицу Inc из предыдущего вопроса, где расходы расположены по столбцам. В ответ запишите элементы из 1 строки этой матрицы через запятую (без пробела):

In [16]:
After_Taxes = Inc * 0.87

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

In [17]:
After_Taxes - Cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

В произведении C = AB матриц

In [18]:
A = np.array([
    [1, -1, 2, 4, 0],
    [8, 2, 0, 5, 3],
    [0, 1, 2, 1, 2]])
    
B = np.array([
    [1, 0, 1, 0],
    [0, 0, 2, -1],
    [1, 0, 1, 1],
    [0, 1, 1, 1,],
    [1, 1, 0, -1]])

C = np.dot(A, B)
print(C)
print('C12: ', C[0,1])
print('C34: ', C[2,3])

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]
C12:  4
C34:  0


## Практика. Умножение матриц
### Даны матрица A и вектор x.

In [19]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

print('A:', A)
print('x:', x)

A: [[ 5 -1  3  1  2]
 [-2  8  5 -1  1]]
x: [1 2 3 4 5]


Найдите произведение матрицы  и вектора  в том порядке, в котором их можно умножить.

In [20]:
A@x

array([26, 30])

### Даны две матрицы:

In [21]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

print('A:', A)
print('B:', B)

A: [[1 9 8 5]
 [3 6 3 2]
 [3 3 3 3]
 [0 2 5 9]
 [4 4 1 2]]
B: [[ 1 -1  0  1  1]
 [-2  0  2 -1  1]]


In [22]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

## Дана система векторов:

In [23]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Найдите матрицу Грама системы векторов 

In [24]:
xyz_m = np.array([x, y, z])
xyz_m@xyz_m.T


array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

## Задача 4. Условие

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [25]:
import pandas as pd

Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
display(Count_DF)

Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
display(Price_DF)

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

Найдите вектор выручки Бориса.

In [26]:
boris_count = Count_DF.loc['Борис'].values
boris_price = Price_DF.loc['Борис'].values

boris_count * boris_price

array([ 3.6, 52.5,  3. , 25. ,  6. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.
Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [28]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

profit = Count_DF.values * Price_DF.values
display(profit)

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [31]:
salon_com = profit @ com
print(salon_com)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [35]:
stylist_profit = profit @ (1 - com)
print(stylist_profit)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


## Обратная матрица

In [39]:
A = np.array([[1,2], [2,5]])
np.linalg.inv(A)

array([[ 5., -2.],
       [-2.,  1.]])

In [42]:
A = np.array([[2,0,0], [0,1,0], [0,0,4]])
print('deta(A): ', np.linalg.det(A))
print('deta(A): ', np.linalg.det(np.linalg.inv(A)))

deta(A):  7.999999999999998
deta(A):  0.12500000000000003


## Практика. Обратная матрица, ранг, определитель
Дана матрица А

In [46]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

Найдите обратную матрицу к матрице А.

In [47]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

Дана система векторов:

In [49]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Найдите ранг системы векторов v1, v2, v3, v4.

In [50]:
v_sys = np.array([v1, v2, v3, v4])
np.linalg.matrix_rank(v_sys)

4

Найдите матрицу Грама системы векторов v1, v2, v3, v4.

In [52]:
v_gram = v_sys @ v_sys.T
print(v_gram)

[[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


Найдите определитель матрицы Грама системы v1, v2, v3, v4.

In [53]:
np.linalg.det(v_gram)

3716647.9999999995

Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.

In [ ]:
np.linalg.inv(v_gram)