In [1]:
import numpy as np

При работе с двумерными массивами для обращения к элементу мы указываем два индекса, соответствующие номеру строки и номеру столбца. Каждый индекс можно указывать в отдельных квадратных скобках или внутри одной пары скобок через запятую:

In [6]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2]

12

In [7]:
my_array[1,2]

12

### Индексация двумерных массивов имеет следующие особенности:

* при указании только одного индекса из массива будет выделена вся строка, соответствующая указанному индексу;
* можно указывать несколько индексов или срезов для каждой из осей.
Поэкспериментируйте с индексацией двумерного массива, используя образец:

In [8]:
my_array[1]

array([10, 11, 12, 13])

In [9]:
my_array[:,2]

array([ 3, 12, 47])

In [10]:
my_array[1:,1:3]

array([[11, 12],
       [46, 47]])

### Упражнения
Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические действия. Задания блока будем выполнять на примере массива, созданного кодом:

In [13]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
print(big_secret)

[[1.40000000e+01 1.00000000e+01 6.00000000e+00 5.60000000e+01
  4.00000000e+01 2.40000000e+01 9.80000000e+01 7.00000000e+01
  4.20000000e+01 1.40000000e+02 1.00000000e+02 6.00000000e+01
  1.82000000e+02 1.30000000e+02 7.80000000e+01 2.24000000e+02
  1.60000000e+02 9.60000000e+01 2.66000000e+02 1.90000000e+02
  1.14000000e+02 3.08000000e+02 2.20000000e+02 1.32000000e+02
  3.50000000e+02 2.50000000e+02 1.50000000e+02 3.92000000e+02
  2.80000000e+02 1.68000000e+02 4.34000000e+02 3.10000000e+02
  1.86000000e+02 4.76000000e+02 3.40000000e+02 2.04000000e+02
  5.18000000e+02 3.70000000e+02 2.22000000e+02 5.60000000e+02
  4.00000000e+02 2.40000000e+02 6.02000000e+02 4.30000000e+02
  2.58000000e+02 6.44000000e+02 4.60000000e+02 2.76000000e+02
  6.86000000e+02 4.90000000e+02 2.94000000e+02]
 [3.16227766e+01 3.16543836e+01 3.16859590e+01 3.17175031e+01
  3.17490157e+01 3.17804972e+01 3.18119474e+01 3.18433667e+01
  3.18747549e+01 3.19061123e+01 3.19374388e+01 3.19687347e+01
  3.20000000e+01 3.203

Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [17]:
sum = 0
for x in big_secret[:, -1]:
    sum += x
sum


3154.332495807108

Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [26]:
sum = 0
part = big_secret[:,:5]
for i in range(len(part)):
    sum += part[i,i]
sum

121.37188663699624

Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [44]:
result = 1
part = big_secret[:,-5:]

for i in range(len(part)):
    result = result * part[i,i]
result

341505315559.2347

### Особенность индексирования
Важное отличие массивов NumPy от списков Python — при изменении среза или отдельных элементов все изменения касаются не только самого среза, но и падают в исходный массив, даже если перед внесением изменений срез был сохранён в виде отдельной переменной. Изначально NumPy проектировался для работы с большими массивами данных, поэтому при бесконтрольном копировании фрагментов массивов возникли бы проблемы с быстродействием и памятью.

Создадим массив 4 х 6:

In [48]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[18, 25, 16, 84, 17, 96],
       [22, 55, 86,  2, 78, 23],
       [62,  8, 96, 53, 41, 95],
       [55, 31,  8, 44, 97,  1]])

Массив создаётся с помощью генератора случайных чисел, поэтому при выполнении кода у вас могут получиться другие значения. Выделим из созданного массива квадрат 2 х 2, содержащий 4 элемента, расположенные в центре матрицы:

In [49]:
my_slice = my_array[1:3, 2:4]
my_slice

array([[86,  2],
       [96, 53]])

In [ ]:
Заменим эти элементы на нули и посмотрим, как изменится содержимое исходной матрицы:

In [50]:
my_slice[:] = 0
my_array

array([[18, 25, 16, 84, 17, 96],
       [22, 55,  0,  0, 78, 23],
       [62,  8,  0,  0, 41, 95],
       [55, 31,  8, 44, 97,  1]])

### Упражнения
Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [53]:
for y in range(len(big_secret)):
    for x in range(len(big_secret[y])):
        if x % 2 == 1 and y % 2 == 1:
            big_secret[y, x] = 1
        elif x % 2 == 0 and y % 2 == 0:
            big_secret[y, x] = -1
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [ ]:
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.


In [54]:
sum = 0
part = big_secret[:,:5]
for i in range(len(part)):
    sum += part[i,i]
sum

-1.0

Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [55]:
result = 1
part = big_secret[:,-5:]

for i in range(len(part)):
    result = result * part[i,i]
result

-1.0

### Операции с массивами
Особенностью работы с массивами в NumPy является то, что возможности библиотеки позволяют выполнять любые математические действия с массивами без использования циклов for, благодаря чему вычисления производятся с большой скоростью. В NumPy над массивами можно производить все стандартные арифметические операции.

Операции выполняются поэлементно, поэтому для получения корректного результата размерность массивов должна быть одинаковой. Также можно производить математические операции между массивом и числом.

У нас есть два массива: найдём их сумму, разность, произведение, частное и умножим один из массивов на число:

In [56]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


### Универсальные функции
Универсальными называют функции, которые выполняют поэлементные операции над данными, хранящимися в объектах ndarray.  Большинство универсальных функций относятся к **унарным** операциям и выполняются над каждым элементом массива по очереди. **Унарные операции** — это  и есть операции, которые выполняются над каждым элементом массива по очереди.

Рассмотрим список часто используемых универсальных функций NumPy. При вызове каждой из этих функций необходимо указывать название библиотеки NumPy: np.isnan(имя_массива):

| Функция | Описание |
|---|---|
|abs|	Абсолютное значение целых, вещественных или комплексных элементов массива|
|sqrt|	Квадратный корень каждого элемента массива|
|exp|	Экспонента (ex) каждого элемента массива|
|log, log10, log2, log1p|	Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно|
|modf|	Дробные и целые части массива в виде отдельных массивов|
|isnan|	Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)|
|cos, sin, tan|	Обычные тригонометрические функции|
|arccos, arcsin, arctan|	Обратные тригонометрические функции|

### Изменение размерности массива
В некоторых задачах машинного обучения для подготовки данных к обработке нужно изменить исходную форму массива, например, преобразовать многомерный массив в одномерный, поменять местами строки и столбцы.

Замена местами строк и столбцов двумерного массива называется транспонированием. Для выполнения этой операции в NumPy используется метод T:

In [58]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Для превращения массива одной размерности в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод reshape. Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:

In [61]:
my_array = np.random.randint(0, 10, 20)
my_array

array([4, 8, 5, 4, 4, 3, 4, 9, 0, 0, 3, 0, 1, 6, 8, 4, 4, 3, 5, 5])

In [62]:
my_array.reshape((4,5))

array([[4, 8, 5, 4, 4],
       [3, 4, 9, 0, 0],
       [3, 0, 1, 6, 8],
       [4, 4, 3, 5, 5]])

Для преобразования многомерного массива в одномерный используется метод flatten:

In [63]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [64]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

### Сравнения и маски
Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10. При создании массива используется генератор случайных чисел, так что у вас могут получиться другие значения:

In [65]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[7, 2, 2, 1],
       [0, 1, 6, 2],
       [3, 2, 1, 6]])

Теперь посмотрим, какие из элементов меньше 5:

In [66]:
my_array < 5

array([[False,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

Мы получили новый массив, заполненный значениями True/False в зависимости от того, меньше или больше пяти элемент, находящийся на соответствующей позиции в исходном массиве. Для того, чтобы получить элементы массива my_array, которые меньше пяти, воспользуемся кодом ниже. Отобранные элементы представляют собой одномерный массив.

In [67]:
my_array[my_array<5]

array([2, 2, 1, 0, 1, 2, 3, 2, 1])

Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных. Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду. Выведем первый и третрий столбец массива:

In [72]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[7, 2],
       [0, 6],
       [3, 1]])

### Сортировка двумерных массивов
В двумерных массивах можно выполнять сортировку элементов строк и столбцов:

Сортировка выполняется с помощью функции sort, в качестве параметров функция получает сам массив, а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

Как можно отсортировать элементы строк и столбцов?

Отсортируем элементы строк:

In [74]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[4, 2, 3, 6, 1, 3],
       [8, 2, 1, 6, 4, 9],
       [7, 5, 4, 3, 7, 4],
       [7, 4, 0, 7, 4, 1]])

In [75]:
np.sort(my_array, axis=1)


array([[1, 2, 3, 3, 4, 6],
       [1, 2, 4, 6, 8, 9],
       [3, 4, 4, 5, 7, 7],
       [0, 1, 4, 4, 7, 7]])

In [76]:
np.sort(my_array, axis=0)

array([[4, 2, 0, 3, 1, 1],
       [7, 2, 1, 6, 4, 3],
       [7, 4, 3, 6, 4, 4],
       [8, 5, 4, 7, 7, 9]])

## Упражнения
Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [77]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [ ]:
Сколько столбцов содержит массив great_secret?

In [78]:
len(great_secret[0])

3

In [ ]:
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [84]:
cos = np.cos(great_secret[0])
print(cos)
np.sum(cos)

[ 1.         -0.07074101 -0.76919177]


0.16006721889793019

In [ ]:
Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [86]:
greatest = great_secret[great_secret > 50]
print(greatest)
np.sum(greatest)

[66.66666667 67.33333333 68.         68.66666667 69.33333333 70.
 70.66666667 71.33333333 72.         72.66666667 73.33333333 74.
 74.66666667 75.33333333 76.         76.66666667 77.33333333 78.
 78.66666667 79.33333333 80.         80.66666667 81.33333333 82.
 82.66666667 83.33333333 84.         50.4        84.66666667 50.8
 85.33333333 51.2        86.         51.6        86.66666667 52.
 87.33333333 52.4        88.         52.8        88.66666667 53.2
 89.33333333 53.6        90.         54.         90.66666667 54.4
 91.33333333 54.8        92.         55.2        92.66666667 55.6
 93.33333333 56.         94.         56.4        94.66666667 56.8
 95.33333333 57.2        96.         57.6        96.66666667 58.
 97.33333333 58.4        98.         58.8        98.66666667 59.2
 99.33333333 59.6       ]


5470.0

In [ ]:
Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [90]:
great_secret.flatten()[150]

7.0710678118654755

Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [91]:
last_row = np.sort(great_secret, axis=0)[-1]
print(last_row)
